export class ExcellentPerformance {

    Id: number;
    BankId: number;
    Status: boolean;
    NetWorthCYP : string;
    NetWorthPYP: string;
    NetWorthOverPYP : string;
    CRAR_CYP : string;
    CRAR_PYP : string;
    DepositCY: number;
    DepositPY: number;
    TDepositOverPYP: string;
    TAdvancesCY: number;
    TAdvancesPY: number;
    TAdvancesOverPYP: string;
    GROSSNPAlnCY : string;
    GROSSNPAlnPY: string;
    TGrossNPAOverPYP: string;
    NetNPACY: number;
    NetNPAPY: number;
    TNetNPAOverPYP : string;
    ReturnOnAssetsInCY: number;
    ReturnOnAssetsPY: number;
    TReturnOnAssetsOverPYP : string; 
    PerEmpBusinessCY: number;
    PerEmpBusinessPY: number;
    TPerEmpBusinessOverPYP : string;
    NetProfitToTAssetsCY : number;
    NetProfitToTAssetsPY: number;
    TNetProfitToTAssetsPY : string;
    CRROrSLROccuredCY: string;
    CRROrSLROccuredPY: string;
    RBIImposePenaltyCY : string;
    RBIImposePenaltyPY : string;
    ShowcaseNotice: string;
    EnquiryByRBI_IncomeTax: string;
    UPIorCKYCImplemented: string;
    KYCWithAML: string;
    BorrowerRatings: string;
    PermissionOpenBranchPY: boolean;
    UniqueIdToCustomer: boolean;
    GotAnyAward: boolean;
    NetOrMobileBankingFacility: boolean;
    M1 : number;
    M2 : number;
    M3 : number;
    M4 : number;
    M5 : number;
    M6 : number;
    M7 : number;
    M8 : number;
    M9 : number;
    M10 : number;
    M11 : number;
    M12 : number;
    M13 : number;
    M14 : number;
    M15 : number;
    M16 : number;
    M17 : number;
    M18 : number;
    M19 : number;
    M20 : number;
    M21 : number;
    M22 : number;
    M23 : number;
    M24 : number;
    M25 : number;
    M26 : number;
    M27 : number;
    M28 : number;
    M29 : number;
    M30 : number;
    M31 : number;
    M32 : number;
    M33 : number;
    M34 : number;
    M35 : number;
    M36 : number;
    M37 : number;
    M38 : number;
    M39 : number;
     
}