export class ExcellentPerformance {

    Id: number;
    BankId: number;
    Status: boolean;
    NetWorthCurrentYrInPercentage: string;
    NetWorthPreviousYrInPercentage: string;
    NetWorthOverPreviousYrInPercentage: string;
    CRARCurrentYrInPercentage: string;
    CRARPreviousYrInPercentage: string;
    DepositCurrentYr: number;
    DepositPreviousYr: number;
    TotalDepositOverPreviousYrInPercentage: string;
    TotalAdvancesCurrentYr: number;
    TotalAdvancesPreviousYr: number;
    TotalAdvancesOverPreviousYrInPercentage: string;
    GrossNPAInCurrentYr: string;
    GrossNPAInPreviousYr: string;
    TotalGrossNPAOverPreviousYrInPercentage: string;
    NetNPACurrentYr: number;
    NetNPAPreviousYr: number;
    TotalNetNPAOverPreviousYrInPercentage: string;
    ReturnOnAssetsInCurrentYr: number;
    ReturnOnAssetsInPerviousYr: number;
    TotalReturnOnAssetsOverPreviousYrInPercentage: string; 
    PerEmpBusinessCurrentYr: number;
    PerEmpBusinessPreviousYr: number;
    TotalPerEmpBusinessOverPreviousYrInPercentage: string;
    NetProfitToTotalAssetsCurrentYr: number;
    NetProfitToTotalAssetsPreviousYr: number;
    TotalNetProfitToTotalAssetsOverPreviousYrInPercentage: string;
    CRROrSLROccuredDuringCurrentYr: string;
    CRROrSLROccuredDuringPreviousYr: string;
    RBIImposeAnyPenaltyDuringCurrentYr: string;
    RBIImposeAnyPenaltyDuringPreviousYr: string;
    ShowcaseNotice: string;
    EnquiryByRBI_IncomeTax: string;
    UPIorCKYCImplemented: string;
    KYCImplementationWithAML: string;
    BorrowerRatings: string;
    PermissionToOpenBranchesInPreviousYr: boolean;
    UniqueIdToCustomer: boolean;
    GotAnyAward: boolean;
    NetOrMobileBankingFacility: boolean;
    M1 : number;
    M2 : number;
    M3 : number;
    M4 : number;
    M5 : number;
    M6 : number;
    M7 : number;
    M8 : number;
    M9 : number;
    M10 : number;
    M11 : number;
    M12 : number;
    M13 : number;
    M14 : number;
    M15 : number;
    M16 : number;
    M17 : number;
    M18 : number;
    M19 : number;
    M20 : number;
    M21 : number;
    M22 : number;
    M23 : number;
    M24 : number;
    M25 : number;
    M26 : number;
    M27 : number;
    M28 : number;
    M29 : number;
    M30 : number;
    M31 : number;
    M32 : number;
    M33 : number;
    M34 : number;
    M35 : number;
    M36 : number;
    M37 : number;
    M38 : number;
    M39 : number;
     
}